repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.7.0
    hooks:
      - id: helm-docs
