---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shutdown-pod-cleaner
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "common.labels" . | indent 4 }}
  annotations:
  {{- include "common.annotations" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shutdown-pod-cleaner-cluster
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "common.labels" . | indent 4 }}
  annotations:
  {{- include "common.annotations" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: shutdown-pod-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: shutdown-pod-cleaner
  apiGroup: ""